import type { GraphEdge, GraphNode } from '../types';
import { getPageAdvice, getSiteAdvice } from './advice';

function fmt(v: number | null | undefined, decimals = 3): string {
  if (v == null) return '—';
  return typeof v === 'number' ? v.toFixed(decimals) : String(v);
}

function bool(v: boolean | null | undefined): string {
  if (v == null) return '—';
  return v ? '✓' : '✗';
}

export function generateMarkdownReport(
  domain: string,
  nodes: GraphNode[],
  edges: GraphEdge[],
): string {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const sorted = [...nodes].sort(
    (a, b) => (b.pagerank ?? 0) - (a.pagerank ?? 0),
  );

  const siteAdvice = getSiteAdvice(nodes);
  const issues: string[] = siteAdvice
    .filter((a) => a.severity === 'warn')
    .map((a) => `- ⚠️ **${a.title}**: ${a.detail}`);
  const goodItems: string[] = siteAdvice
    .filter((a) => a.severity === 'good')
    .map((a) => `- ✅ **${a.title}**: ${a.detail}`);

  const avgLoad =
    nodes.filter((n) => n.load_time_ms != null).length > 0
      ? Math.round(
          nodes.reduce((s, n) => s + (n.load_time_ms ?? 0), 0) /
            nodes.filter((n) => n.load_time_ms != null).length,
        )
      : null;
  const noMeta = nodes.filter((n) => n.has_meta_description === false).length;
  const noH1 = nodes.filter((n) => n.h1_count === 0).length;
  const orphans = nodes.filter((n) => n.in_degree === 0 && (n.depth ?? 0) > 0).length;
  const deadEnds = nodes.filter((n) => n.out_degree === 0).length;
  const errors = nodes.filter((n) => n.status_code != null && n.status_code >= 400).length;

  const pageTable = [
    '| # | Path | PR | In | Out | Depth | Load(ms) | Words | H1 | Meta | Status |',
    '|---|------|----|----|-----|-------|----------|-------|----|------|--------|',
    ...sorted.map((n, i) =>
      `| ${i + 1} | ${n.label} | ${fmt(n.pagerank)} | ${n.in_degree} | ${n.out_degree} | ${n.depth ?? '—'} | ${n.load_time_ms ?? '—'} | ${n.word_count ?? '—'} | ${n.h1_count ?? '—'} | ${bool(n.has_meta_description)} | ${n.status_code ?? '—'} |`,
    ),
  ].join('\n');

  const issueDetails = buildIssueDetails(nodes);

  const lines: string[] = [
    `# WebGraph Site Analysis — ${domain}`,
    `**Generated:** ${now} · **Pages:** ${nodes.length} · **Links:** ${edges.length}`,
    '',
    '> **How to use:** Paste this report into Claude or ChatGPT and ask:',
    '> *"Analyze this website\'s internal link structure and SEO health. List the top 5 improvements I should make, ordered by impact."*',
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total pages | ${nodes.length} |`,
    `| Total internal links | ${edges.length} |`,
    `| Avg server response | ${avgLoad != null ? avgLoad + ' ms' : '—'} |`,
    `| Orphan pages | ${orphans} |`,
    `| Dead-end pages | ${deadEnds} |`,
    `| Pages missing meta description | ${noMeta} |`,
    `| Pages without H1 | ${noH1} |`,
    `| Pages with HTTP errors | ${errors} |`,
    '',
    '## Site-wide Observations',
    '',
    ...(issues.length > 0 ? ['### Issues', ...issues, ''] : []),
    ...(goodItems.length > 0 ? ['### Strengths', ...goodItems, ''] : []),
    '## All Pages (sorted by PageRank)',
    '',
    pageTable,
    '',
    '## Issues by Category',
    '',
    issueDetails,
    '## Per-page Advice',
    '',
    ...sorted.flatMap((node) => {
      const advice = getPageAdvice(node, nodes).filter((a) => a.severity !== 'good');
      if (advice.length === 0) return [];
      return [
        `### ${node.title || node.label} \`${node.label}\``,
        ...advice.map((a) => `- **[${a.severity.toUpperCase()}] ${a.title}**: ${a.detail}`),
        '',
      ];
    }),
    '---',
    `*Report generated by [WebGraph Viz](https://github.com/BeastOfShadow/webgraph-viz)*`,
  ];

  return lines.join('\n');
}

function buildIssueDetails(nodes: GraphNode[]): string {
  const sections: string[] = [];

  const noMeta = nodes.filter((n) => n.has_meta_description === false);
  if (noMeta.length > 0) {
    sections.push(
      `### Missing meta description (${noMeta.length})`,
      ...noMeta.map((n) => `- \`${n.label}\` — ${n.url}`),
      '',
    );
  }

  const noH1 = nodes.filter((n) => n.h1_count === 0);
  if (noH1.length > 0) {
    sections.push(
      `### No H1 tag (${noH1.length})`,
      ...noH1.map((n) => `- \`${n.label}\``),
      '',
    );
  }

  const multiH1 = nodes.filter((n) => (n.h1_count ?? 0) > 1);
  if (multiH1.length > 0) {
    sections.push(
      `### Multiple H1 tags`,
      ...multiH1.map((n) => `- \`${n.label}\` — ${n.h1_count} H1s`),
      '',
    );
  }

  const slow = nodes
    .filter((n) => n.load_time_ms != null && n.load_time_ms > 1000)
    .sort((a, b) => (b.load_time_ms ?? 0) - (a.load_time_ms ?? 0));
  if (slow.length > 0) {
    sections.push(
      `### Slow pages (>1 s response)`,
      ...slow.map((n) => `- \`${n.label}\` — ${n.load_time_ms} ms`),
      '',
    );
  }

  const orphans = nodes.filter((n) => n.in_degree === 0 && (n.depth ?? 0) > 0);
  if (orphans.length > 0) {
    sections.push(
      `### Orphan pages (no inbound internal links)`,
      ...orphans.map((n) => `- \`${n.label}\``),
      '',
    );
  }

  const errors = nodes.filter((n) => n.status_code != null && n.status_code >= 400);
  if (errors.length > 0) {
    sections.push(
      `### HTTP errors`,
      ...errors.map((n) => `- \`${n.label}\` — HTTP ${n.status_code}`),
      '',
    );
  }

  return sections.join('\n');
}

export function downloadReport(domain: string, nodes: GraphNode[], edges: GraphEdge[]): void {
  const md = generateMarkdownReport(domain, nodes, edges);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `webgraph-${domain}-${new Date().toISOString().slice(0, 10)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
